mlibrary/search

- src/modules/advanced/components/AdvancedSearch/index.js
- src/modules/pages/components/DatastorePage/container.js
- src/modules/pages/components/RoadMapPage/index.js
- src/modules/records/components/RecordFull/index.js
- src/modules/search/components/HelpContent/index.js
- src/modules/search/components/SearchBox/index.js
https://tools.lib.umich.edu/jira/browse/SEARCH-30
> Updated document title for unique pages SEARCH-30

- src/config/config.js
> Remove superfluous trailing slash

- src/modules/flint/components/FlintAlerts/index.js
- src/modules/flint/components/UserIsFlintAffiliated/index.js
- src/modules/flint/index.js
- src/modules/pages/components/DatastorePage/container.js
- src/modules/reusable/components/Alert/Alert.css
- src/modules/reusable/components/Alert/Alert.scss
- src/modules/reusable/components/Button/Button.css
- src/modules/reusable/components/Button/Button.scss
- src/stylesheets/main.css
- src/stylesheets/main.scss
- src/stylesheets/search/_datastore-info.scss
More details: https://tools.lib.umich.edu/jira/browse/SEARCH-621
Preview of what the flint alert message looks like:
> Flint affiliate messages for search categories

- src/modules/pride/setup.js
This reverts commit 29b288733f7792c607e31c198fbb9843e58d763b.
> Revert "SEARCH-871 quickfix"

- src/modules/resource-acccess/components/holder.js
- Prettier formatting.
- Make ResourceAccess Holder rows optional.
> ResourceAccess Holder rows are optional.

- src/modules/core/components/Feedback/index.js
Refactor Feedback component from a class to functional component for training purposes.
> Refactor Feedback component

- src/config/config.js
toc renamed to contents_listing
> Field name change.

- src/config/config.js
Turns out it was not actually working as intended.
> Remove contents_listing

- src/modules/advanced/components/AdvancedSearchForm/index.js
I have confirmation that the new behavior is closer to expectations.
> SEARCH-1136 Generate parentheses around fielded search text fields

- src/modules/datastores/components/DatastoreAlerts/index.js
- Added requested sentence to Datastores alert.
> COVID alert text update June 29

- public/index.html
- src/modules/core/components/Footer/index.js
More information: https://github.com/mlibrary/design-system#basic-template
> Add <m-universal-header> and replace <Chat /> for <m-chat> web components.

- public/index.html
- Adds Google Tag Manager script
- Some light formatting from Prettier
> SEARCH-1163 Add Google Tag Manager scripts

- src/modules/getthis/components/GetThisFAQ/index.js
Update Get This FAQ for current Get This procedures.
> SEARCH-1220 Update Get This FAQ

- src/modules/getthis/components/GetThisFAQ/index.js
Updating posted FAQ text about what's available for contactless pickup.
Before:
Proposed update:
> Updating Get This FAQ text.

- package-lock.json
- package.json
- src/modules/institution/components/InstitutionSelect/index.js
- src/modules/pages/components/DatastorePage/container.js
- src/modules/pride/setup.js
- src/modules/search/actions/index.js
- src/modules/search/components/SearchParserMessage/index.js
- src/modules/search/index.js
- src/modules/search/reducer/index.js
> Parser messages to state

- src/modules/datastores/components/DatastoreAlerts/index.js
Removal of alert added in v.14.15 for scheduled downtime on 11/21.
> SEARCH-1236 Removal of alert after scheduled downtime.

- src/modules/getthis/components/GetThisPage/index.js
- Remove: "Request books and other media to the campus library or department most convenient for you." This change is a request from AaL.
> SEARCH-1279 Remove text lede from Get This under heading

- src/modules/search/components/SearchResultsMessage/index.js
- src/stylesheets/main.css
This PR addresses updates to work on SEARCH-1277
This work is a result of the recommendations from the user testing and feedback after the initial deployment of the new messaging for the parser message.
Warnings present but not from this work and not in scope to fix at this time.
> User feedback design updates.

- src/config/config.js
- src/modules/core/components/Alert/index.js
- src/modules/datastores/components/DatastoreInfo/index.js
- src/modules/datastores/components/Landing/index.js
- src/modules/flint/components/FlintAlerts/index.js
- src/modules/pages/components/DatastorePage/container.js
- src/modules/pages/components/NoMatch/index.js
- src/modules/pride/browse.js
- src/modules/pride/setup.js
- src/modules/records/components/BentoboxList/index.js
- src/modules/records/components/RecordPreview/index.js
This PR addresses # SEARCH-1256.
Updates Search to display the catalog-based online journals datastore.  
https://deploy-preview-279--umich-lib-search-dev.netlify.app/everything
> SEARCH-1256 Initial changes to add onlinejournals uid to UI

- src/config/config.js
This PR addresses SEARCH-1457: Enabling date sorting for articles
This PR updates the list of which sorting options to include for Articles searches.
- [ x] New feature (non-breaking change which adds functionality)
Ad-hoc  browser testing.
None
> Enable articles sorting.

- src/modules/lists/components/CitationAction/index.js
This PR addresses [SEARCH-1634](https://tools.lib.umich.edu/jira/browse/SEARCH-1634).
* [Citation style (APA, MLA, Chicago, IEEE, BibTex, NLM)][Context (Full (view), List (view)]
* Close
> [SEARCH-1634] GTM Events: Cite This

- src/modules/specialists/components/Specialist/index.js
This PR addresses [SEARCH-1641](https://tools.lib.umich.edu/jira/browse/SEARCH-1641).
* Library Specialist Page - [Librarian's Name (First Name Last Name)]
* Library Specialist Email - [Librarian's Name (First Name Last Name)]
> [SEARCH-1641] GTM Events: Library Specialist

- src/modules/lists/components/GoToList/index.js
This PR addresses [SEARCH-1643](https://tools.lib.umich.edu/jira/browse/SEARCH-1643).
* Access My List
> [SEARCH-1643] GTM Events: My List

- src/modules/lists/components/AddToListButton/index.js
This PR addresses [SEARCH-1647](https://tools.lib.umich.edu/jira/browse/SEARCH-1647).
* List [Add, Remove] 
> [SEARCH-1647] GTM Events: Select

- src/modules/resource-acccess/components/holder-container.js
- src/modules/resource-acccess/components/holders.js
- src/modules/resource-acccess/components/resource-access-container.js
This PR addresses [SEARCH-1645](https://tools.lib.umich.edu/jira/browse/SEARCH-1645).
Go to Item From Availability in [Datastore] [View (Full, Medium)]
Available Online From Online Resources in Catalog [View (Full, Medium)]
Expand [Holding location (Online Resources, HathiTrust Digital Library, Hatcher Graduate...)] From [Datastore][View (Medium, Full)]
Full Text From HathiTrust Digital Library in [Datastore] [View (Full, Medium)]
> [SEARCH-1645] GTM Events: Resource Access

- package-lock.json
- package.json
This pull request updates all packages that only had subversion upgrades.
- `npm run reinstall && npm start`
- Poke around [the site](http://localhost:3000/) and see if anything seems broken.
If you load the site and it produces this error:
- Stop the browser view (`Ctrl + C`).
- `cd node_modules/pride`
- `nano pride.js`
- Replace all instances of `_underscore._.` with `_underscore.` and save.
- `npm install`
- `cd ../../`
- `npm start`
> Update packages (March) - Part 1

- .eslintrc.json
- package-lock.json
- package.json
This pull request relates to LIT's update-a-thon!
Minor updates have been made to `eslint`, `@emotion/react`, `@emotion/styled`, `core-js`, and `connected-react-router`.
> 2022-09-08 Updates

- package-lock.json
- package.json
Updating `eslint`, `eslint-plugin-react`, `react-tabs`, and `regenerator-runtime`.
> November 2022 Updates

- src/modules/core/components/SearchHeader/index.js
This PR addresses [LIBSEARCH-813](https://mlit.atlassian.net/browse/LIBSEARCH-813).
"My Favorites" has been sunsetted and now must be removed from the header. The file involved has also been linted.
> [LIBSEARCH-813] Remove "My Favorites" from Search header

- package-lock.json
- package.json
This pull request contains the latest dependency updates.
> February 2023 dependency updates.

- .github/PULL_REQUEST_TEMPLATE/dependency_updates_template.md
- .github/pull_request_template.md
This pull request template is to help with the automation of monthly updates, by [using query parameters to create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request).
For example: [https://github.com/mlibrary/search/compare/master...dependency-updates-template?quick_pull=1&template=dependency_updates_template.md&labels=dependencies&assignees=erinesullivan](https://github.com/mlibrary/search/compare/master...dependency-updates-template?quick_pull=1&template=dependency_updates_template.md&labels=dependencies&assignees=erinesullivan)
The default template has also been updated to include more specific information.
> Adding Dependency Updates pull request template.

- src/modules/affiliation/components/choose-affiliation.js
While adding [accessibility fixes](https://github.com/mlibrary/search/pull/388), the [Dialog](https://github.com/mlibrary/search/blob/master/src/modules/reusable/components/Dialog/index.js) component was created. The component uses the native `<dialog>` HTML5 element, and is controlled by the [`close()` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close) to close the element. Three weeks after launching the changes, [a user reported](https://teamdynamix.umich.edu/TDNext/Apps/87/Tickets/TicketDet?TicketID=4598074) that the site would not load for them in Safari. It turns out that the `close()` method is [not supported by Safari older than 15.4](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close#browser_compatibility). The percentage of …
> Bug: Fixing `Dialog` for Safari < 15.4.

- .github/PULL_REQUEST_TEMPLATE/dependency_updates_template.md
Adding a section called `Workflows` to use as a reminder to also stay on top of build actions during monthly updates.
> Adding section for workflows in PR template.

- src/modules/core/components/TrimString/index.js
- src/stylesheets/main.css
To align with [current React practices](https://react.dev/learn/your-first-component), the `TrimString` class component has been converted to a functional component. The code and styling have also been simplified.
- Find [a record with a really long name](http://localhost:3000/articles/record/cdi_proquest_journals_1683851788?query=The+Historical+Development+of+the+Heart+from+Its+Formation+From).
- Is it truncated?
- Does a `Show more` button appear in the full record view?
- When you click the button, does it show the whole name?
- Does the button read `Show less`?
- Do the other records in the record list not have an ellipsis if their names are short enough?
> Converting `TrimString` to a functional component.

- package-lock.json
- package.json
Installing dependencies and building the site produced several errors and warnings. This pull request rebuilds all `overrides` to remove all messages.
- Do a clean install and run the site. Do any messages pop up?
> Resolving vulnerabilities.

- .github/PULL_REQUEST_TEMPLATE/dependency_updates_template.md
- package-lock.json
- package.json
Monthly dependency update to help maintain Search.
These dependencies have been updated to their latest versions:
- `@eslint/compat`
- `@eslint/js`
- `@reduxjs/toolkit`
- `eslint`
- `eslint-plugin-react`
- `globals`
- Install the updated packages (`npm install`).
- Start [the site](http://localhost:3000/everything) to see if everything still works (`npm start`).
> 2024 06 04 updates

- package-lock.json
- package.json
- src/modules/advanced/components/FiltersContainer/index.js
- src/modules/browse/components/BrowseByFilters/index.js
- src/modules/core/components/DateRangeInput/index.js
- src/modules/filters/components/Filters/index.js
- src/modules/getthis/components/GetThisFindIt/index.js
- src/modules/getthis/components/GetThisForm/index.js
- src/modules/getthis/components/GetThisOption/index.js
- src/modules/getthis/components/GetThisOptions/index.js
- src/modules/getthis/components/GetThisPage/index.js
- src/modules/lists/components/CitationAction/index.js
- src/modules/lists/components/List/index.js
- src/modules/pages/components/DatastorePage/index.js
- src/modules/records/components/RecordList/index.js
Monthly dependency update to help maintain Search.
These dependencies have been updated to their latest versions:
- `@eslint/compat`
- `@eslint/js`
- `@reduxjs/toolkit`
- `@stylistic/eslint-plugin`
- `eslint`
- `eslint-plugin-react`
- `globals`
- `react-router-dom`
- Install the updated packages (`npm install`).
- Start [the site](http://localhost:3000/everything) to see if everything still works (`npm start`).
> July 2024 dependency updates.

- package-lock.json
- package.json
Monthly dependency update to help maintain Search.
These dependencies have been updated to their latest versions:
- `@eslint/compat`
- `@eslint/js`
- `@reduxjs/toolkit`
- `@stylistic/eslint-plugin`
- `citeproc`
- `eslint`
- `eslint-plugin-react`
- `globals`
- `qs`
- `react-router-dom`
- Install the updated packages (`npm install`).
- Start [the site](http://localhost:3000/everything) to see if everything still works (`npm start`).
> September 2024 dependency updates.

- package-lock.json
- package.json
Monthly dependency update to help maintain Search.
These dependencies have been updated to their latest versions:
- `@eslint/compat`
- `@eslint/js`
- `@stylistic/eslint-plugin`
- `eslint`
- `eslint-plugin-react`
- `globals`
- `react-router-dom`
- Install the updated packages (`npm install`).
- Start [the site](http://localhost:3000/everything) to see if everything still works (`npm start`).
> October 2024 dependency updates.

- src/modules/datastores/components/DatastoreInfoContainer/index.js
- src/modules/datastores/components/DatastoreMain/index.js
- src/modules/datastores/components/DatastoreNavigation/index.js
- src/modules/datastores/components/DatastoreRoute/index.js
- src/modules/datastores/components/FlintAlerts/index.js
- src/modules/datastores/components/Landing/index.js
- src/modules/datastores/index.js
- src/modules/institution/components/InstitutionSelect/index.js
- src/modules/lists/components/ActionsList/index.js
- src/modules/lists/components/CitationAction/index.js
- src/modules/lists/components/List/index.js
- src/modules/pages/components/DatastorePage/index.js
- src/modules/pride/components/URLSearchQueryWrapper/index.js
- src/modules/records/components/Results/index.js
- src/modules/reusable/components/ContextProvider/index.js
- src/modules/search/components/SearchBox/index.js
A lot of information is being loaded in `DatastorePage`. To help increase performance, variable assignments have been destructured, unused properties have been removed, and properties have been refined so it's only receiving the necessary information.
`DatastoreMain` has been created and all related components and `useSelector` assignments have been moved to that, so they do not need to be loaded whenever `DatastorePage` is loaded.
- Check through the site to see if anything is broken.
> Improve DatastorePage

- src/modules/reusable/components/Dialog/index.js
- src/modules/reusable/components/Dialog/styles.css
- src/stylesheets/main.css
In preparation for the Search rebuild, it is important to make sure styles match. This pull request updates `dialog` and `button` styles.
- Poke around the site to make sure nothing is broken.
> Dialog and button updates

- package.json
- public/citations/locales-en-US.xml
This updates public/citations/locales-en-US.xml, and adds updating it to the `update:csl` npm script.
> Updating the CSL locales file, too.

- src/modules/browse/components/ShelfBrowse/index.js
- src/modules/browse/components/ShelfBrowseCarousel/index.js
Syndetic Solutions API has officially been purchased and now can be applied to show the book covers for the Shelf Browse Carousel.
This pull request closes [LIBSEARCH-1032](https://mlit.atlassian.net/browse/LIBSEARCH-1032).
- Check to see if the images load.
> [LIBSEARCH-1032] Test an integration of book covers from Syndetic Solutions in the shelf carousel

- package.json
- src/modules/pride/components/URLSearchQueryWrapper/index.js
- src/modules/pride/setup.js
<details open>
<summary> :hand:&nbsp;&nbsp;<strong>Wait!</strong></summary>
Let's make sure your pull request is ready. Ask yourself...
:white_check_mark:&nbsp;&nbsp;"Did I do a good job testing my own code?"
:white_check_mark:&nbsp;&nbsp;"Is my code easy to read and understand?"
:white_check_mark:&nbsp;&nbsp;"Have I written unit tests? Do the unit tests fully cover my code?"
:white_check_mark:&nbsp;&nbsp;"Have I tested the repository's behavior to make sure my code didn't break anything?"
:negative_squared_cross_mark:&nbsp;&nbsp;"Did I include unrelated work that could be in its own pull request?"
Once you are ready, be sure to delete this `details` section before opening your pull request.
</details>
Talk about the intent and scope of the original issue. Go over the general changes that …
> Update build dev

- package-lock.json
- package.json
Running `npm start` was throwing an error. The repository was reverted to the previous updates, ran `npm-check-updates`, and did a clean install.
> Bug: `npm start`
