mlibrary/search

- src/config/config.js
Some filter values don't apply cleanly.  The ones with parens and/or plus signs.  May be an encoding issue along the way.
I also did want to map to the uid `access_type`, but that was afflicted by the other filtering bug.  Maybe when the other bug is fixed.
> Update access type.

- src/config/config.js
Now that SEARCH-307 is fixed, we can rename the field here.
> Fix the access_type field name

- src/modules/pride/setup.js
This improved the situation we experienced where subject specialists from inactive results overwrite specialists from the active results.  This is especially prominent for searchers where the academic discipline filter is applied.
> Add specialists from the active datastore only

- src/modules/getthis/components/GetThisRecord/index.js
- src/modules/records/components/RecordFull/index.js
- src/modules/records/components/RecordFullFormats/index.js
- src/modules/records/utilities/index.js
Clean up unused variables and code now that formats are a top-level attribute on records.
> Have `RecordFullFormats` use `record.formats`.

- src/index.js
As requested in SEARCH-1155, urls with /librarywebsite will redirect to /guidesandmore and carry over the search parameters.
> SEARCH-1155 Add redirect for librarywebsite to guides

- src/modules/advanced/components/FieldInput/index.js
- src/modules/search/components/SearchBox/index.js
Hotjar suppresses keystroke by default. This PR adds the `data-hj-allow` attribute to the basic and advanced search inputs.
Documentation: [How to Show Elements and Keystroke in Data Collection ](https://help.hotjar.com/hc/en-us/articles/115015563287-How-to-Show-Elements-and-Keystrokes-in-Data-Collection)
> SEARCH-1169 Add hotjar allow data attribute to search inputs

- src/modules/advanced/components/AdvancedFilter/index.js
Noticed that there aren't spaces as described, resulting in
`after2002` as opposed to `after 2002`.
> Add spaces between date descriptors (before/after) and the date

- src/modules/datastores/components/DatastoreAlerts/index.js
Updating alert in production for scheduled downtime for SEARCH-1236..
"Alert text:
Some Library Search features, including contactless pickup requests, and My Account features, including checkouts, checkout history, and fines/fees, in addition to access to Mirlyn Classic, will be unavailable from 8AM to noon on Saturday, November 21, for system maintenance."
> SEARCH-1236 Alert message for Nov 21 downtime.

- src/modules/getthis/components/GetThisFAQ/index.js
Adding text to the Get This FAQ to clarify what to do (who to contact) if a volume is not in ETAS and not listed for contactless pick up (technical/data issue).
> SEARCH-1245 Add information to Get This FAQ

- src/modules/pages/components/DatastorePage/container.js
- src/modules/records/components/RecordList/index.js
This PR addresses # [SEARCH-1280](https://tools.lib.umich.edu/jira/browse/SEARCH-1280) and [SEARCH-1287](https://tools.lib.umich.edu/jira/browse/SEARCH-1287)
SEARCH-1280 removes the COVID-19 alert from the front-end as it has been replaced with the alerts packaged with the universal header.
SEARCH-1287 updates the messaging a user receives when they have "No Results" for a search. I updated the list items with documentation provided to me. Additionally, there is now a dynamic link to Advanced Search that recognizes which datastore you are on and takes to to to the Advanced tab for that datastore.
SEARCH-1280 The COVID-19 alert no longer appears.
SEARCH-1287 Inserting "_" into the Search bar gives No Results. I can see the updated text changes. Additionally, choosing the advanced search …
> Testing updates

- package-lock.json
- src/modules/pages/components/DatastorePage/container.js
- src/modules/pride/components/URLSearchQueryWrapper/index.js
- src/modules/records/components/RecordList/index.js
- src/modules/search/components/SearchParserMessage2/index.js
- src/modules/search/components/SearchResultsMessage/index.js
- src/modules/search/index.js
- src/stylesheets/main.css
This PR addresses # SEARCH-1277
Replaces the parser message modal component(SearchParserMessage) to a message component in the results container (SearchResultsMessage) on the RecordList. A search query should show under the number of results and if the QP changed the query, the message appears. The message won't show unless running the parser_testing_1 data.
To test locally, pull branch and `npm run start:kub`
> SEARCH-1277 | Qp message

- src/modules/pages/components/DatastorePage/container.js
This PR addresses # SEARCH-1342
We previously removed the in-page COVID Datastore alert message on testing in order to use the new website alert system. In transitioning the use of the UH system on Search, we are removing this duplicate messaging system.
Please delete options that are not relevant.
[Preview](https://deploy-preview-278--umich-lib-search-dev.netlify.app/)
> SEARCH-1342 Remove in-page Covid Datastore Alert for production.

- src/modules/records/components/RecordFull/index.js
This PR addresses # SEARCH-1358
When someone goes to a record page with a 9-digit ID, and we get a record back that doesn't match ID, assume that we've gotten an aleph ID and redirect to the id in the id field on the record.
I have no idea if this is the right way to do this - it worked well enough for testing, but I don't know React idioms. Spectrum PR [https://github.com/mlibrary/spectrum-json/pull/25](#25) - redirect from old aleph_id to new alma id) requires this or some similar change for the user to actually see the record they asked for instead of Search infinitely looping trying to fetch a record with a matching ID in the `id` field.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions to reproduce.
> Redirect if we have a record w/ wrong, aleph-looking id

- src/modules/core/components/SearchHeader/index.js
"My Account" has be named to just "Account" and it now lives at account.lib.umich.edu. This PR changes that link.
> "My Account" => "Account" -- SEARCH-1394

- src/modules/core/components/Footer/index.js
This PR addresses [SEARCH-1521](https://tools.lib.umich.edu/jira/browse/SEARCH-1521).
The copyright year in the footer was static text, and has not been updated since `2018`. This pull request updates that so it will automatically change every year.
This has been tested on `localhost`. Several pages have been looked at to see if the footer has been updated throughout.
> [SEARCH-1521] Update copyright in footer of Search to reflect current year

- src/modules/search/search-options.js
The tips contained some typos, mainly based on period placements.
This pull request resolves [SEARCH-1564](https://tools.lib.umich.edu/jira/browse/SEARCH-1564).
- On [localhost](http://localhost:3000/catalog?library=All+libraries), check the tip under the search form.
- Does the tip for the default selected option appear on load?
- When you select a different option, does the tip change?
- Does the tip change when you try to select a disabled option?
> [SEARCH-1564] Browse Tip Typos

- public/index.html
- src/modules/core/components/Footer/index.js
- src/modules/core/components/SearchHeader/index.js
- src/modules/search/components/SearchBox/index.js
In an effort to expand Google Tag Manager (GTM) events, a custom event had to be created for whenever a user makes a change in the Search Box dropdown. 
This PR addresses [SEARCH-1571](https://tools.lib.umich.edu/jira/browse/SEARCH-1571).
In the future, the plan is to take all of the hardcoded GTM events and set them up in the admin for more available control, according to the [Event Tracking Documentation](https://docs.google.com/spreadsheets/d/1WPdSqGcTI98l5nMBgvuIm9jUYE0MPGl45JxHk4wqTRw/edit?usp=sharing). This PR converts the Footer events, as a start.
There were many warnings relating to React on the home page, so some fixes have been applied.
Children elements require a unique `key` attribute, so they have been added wherever they were missing.
The `Icon` component coming from …
> [SEARCH-1571] Add tracking for search dropdown menu

- src/modules/advanced/components/AdvancedSearchForm/index.js
This PR addresses [SEARCH-1627](https://tools.lib.umich.edu/jira/browse/SEARCH-1627)
When doing a basic `Keyword` search, the input is strictly the original value. When searching any other field, the value gets wrapped in the query (e.g. `author:(...)`). But when doing an advanced `Keyword` search, the query returns `keyword:(...)` instead of the original value. The advanced search now checks to see if the `Keyword` field has been selected and will return just the value without the wrap. 
- Go to advanced search, and make a `Keyword` search.
- Check to see if the value returns as is and not `keyword:(...)`.
- Make an advanced search using any other field, and see that the value is wrapped.
> [SEARCH-1627] Database advanced keyword searches not being parsed correctly

- src/modules/lists/components/ActionsList/index.js
This PR addresses [SEARCH-1630](https://tools.lib.umich.edu/jira/browse/SEARCH-1630)
* Activated [Action type (Email, Text, Citation, Endnote, Ris, Favorite, Permalink)] (*Indicates that the action was clicked and the action form expanded)
* Use [Action (Email, Text, Citation, Endnote, Ris, Favorite, Permalink)](*Indicates that the action was submitted (clicked) with the button)
> [SEARCH-1630] GTM Events: Actions

- src/modules/records/components/BentoboxList/index.js
- src/modules/records/components/RecordPreview/index.js
This PR addresses [SEARCH-1631](https://tools.lib.umich.edu/jira/browse/SEARCH-1631)
* All [Datastore (Mirlyn (*Used for Catalog), Articlesplus (*Used for Articles), Primo (*Used for Primo), Databases, Journals, Onlinejournals, Website (*Used for Guides and More)] Results header
* All [Datastore (Mirlyn (*Used for Catalog), Articlesplus (*Used for Articles), Primo (*Used for Primo), Databases, Journals, Onlinejournals, Website (*Used for Guides and More)] Results Footer
* Full View From Brief [Datastore (Mirlyn (*Used for Catalog), Articlesplus (*Used for Articles), Primo (*Used for Primo), Databases, Journals, Onlinejournals, Website (*Used for Guides and More)]
* [Datastore (Articlesplus (*Used for Articles), Primo (*Used for Catalog since …
> [SEARCH-1631] GTM Events: Brief View

- src/modules/browse/components/BrowseInfo/index.js
This PR addresses [SEARCH-1632](https://tools.lib.umich.edu/jira/browse/SEARCH-1632)
* Go to [Database Browse, Online Journal Browse]
> [SEARCH-1632] GTM Events: Browse

- src/modules/reusable/components/Pagination/Pagination.js
This PR addresses [SEARCH-1633](https://tools.lib.umich.edu/jira/browse/SEARCH-1633), and [SEARCH-1644](https://tools.lib.umich.edu/jira/browse/SEARCH-1644).
* [(Previous, Next)] Page
* Page Number [page number from which a page change occurs in search results]
> [SEARCH-1633] and [SEARCH-1644] GTM Events: Change Page and Page Change

- src/modules/datastores/components/DatastoreNavigation/presenter.js
This PR addresses [SEARCH-1635](https://tools.lib.umich.edu/jira/browse/SEARCH-1635).
* [Datastore (Everything, Catalog, Articles, Articles via Primo API, Articles via Summon API, Primo Articles, Summon Articles, Databases, Online Journals, Guides and More)] 
> [SEARCH-1635] GTM Events: Datastore Navigation

- src/modules/favorites/components/FavoriteRecord/index.js
- src/modules/favorites/components/FavoriteTags/index.js
This PR addresses [SEARCH-1636](https://tools.lib.umich.edu/jira/browse/SEARCH-1636).
* Save Favorite Item From [(Datastore name) Medium Record, (Datastore name) Full Record]
* Remove Favorite Item From [(Datastore name) Medium Record, (Datastore name) Full Record]
* Add Tag [(Datastore) Medium View, (Datastore) Full View]
* Remove Tag [(Datastore) Medium View, (Datastore) Full View]
> [SEARCH-1636] GTM Events: Favorites

- src/modules/institution/components/InstitutionSelect/index.js
This PR addresses [SEARCH-1637](https://tools.lib.umich.edu/jira/browse/SEARCH-1637).
* Change Scope to [U-M Ann Arbor Libraries, All Libraries, Thompson Library, Clements Library, Bentley Historical Library] 
> [SEARCH-1637] GTM Events: Filter

- src/modules/getthis/components/GetThisForm/index.js
- src/modules/getthis/components/GetThisOption/index.js
This PR addresses [SEARCH-1640](https://tools.lib.umich.edu/jira/browse/SEARCH-1640).
* [Get This option (Contactless Pickup, Request to Have a Small Portion Scanned (Document Deivery), Have it Delivered, Find It in the Library, Request a Copy From Another Library (Interlibrary Loan (I.L.L.)), Request That This Copy Be Returned, Full Text Available Online, Place a Future Reservation, Pick It Up at the Library (Library to Library), Request a Digital Copy (Interlibrary Loan (I.L.L.)), Contact Circulation, Request Cannot Be Placed] -- [Open or Closed (*user clicked on the accordion to open/close the option in the Get This page)]
> [SEARCH-1640] GTM Events: Item Request

- src/modules/records/components/Record/index.js
This PR addresses [SEARCH-1642](https://tools.lib.umich.edu/jira/browse/SEARCH-1642).
* Full View From Medium [Datastore (Mirlyn (*Used for Catalog), Articlesplus (*Used for Articles), Primo (*Used for Primo), Databases, Journals, Onlinejournals, Website (*Used for Guides and More)] 
> [SEARCH-1642] GTM Events: Medium View

- src/modules/advanced/components/AdvancedSearchForm/index.js
This PR addresses [SEARCH-1646](https://tools.lib.umich.edu/jira/browse/SEARCH-1646).
* Advanced Search [Datastore (Everything, Catalog, Articles, Databases, Online Journals, Guides and More)]
> [SEARCH-1646] GTM Events: Search Button

- src/modules/favorites/components/FavoriteRecord/index.js
- src/modules/records/components/Sorts/index.js
This PR addresses [SEARCH-1648](https://tools.lib.umich.edu/jira/browse/SEARCH-1648).
Change Sort to [Date_Desc, Date_Asc, Relevance, Title_asc, Date_added, Auth_asc, Title_desc, Author_desc]
> [SEARCH-1648] GTM Events: Sort By

- src/modules/search/components/SearchBox/index.js
- src/modules/search/search-options.js
This PR addresses [SEARCH-1654](https://tools.lib.umich.edu/jira/browse/SEARCH-1654)
Search tips was originally added to the `Catalog` datastore. Now it is to be added to the `Articles` datastore!
Please delete options that are not relevant.
Insert screen shot, video, or deploy preview link. Add captions for images.
> [SEARCH-1654] Add search hints to Articles pages

- src/modules/records/components/RecordFull/index.js
- src/modules/search/search-options.js
This PR addresses [SEARCH-1598](https://tools.lib.umich.edu/jira/browse/SEARCH-1598).
The library has issued a [Statement on Remediation of Harmful Metadata](https://www.lib.umich.edu/about-us/policies/remediation-harmful-language-library-metadata) on the public website. 
DAAG has requested that we add a statement to Catalog and Online Journal records letting users know they can raise concerns.
- Search for an item that shows up in each datastore and select a record.
- See if the harmful remediation only shows up if the record falls under `Catalog` or `Online Journals`.
> [SEARCH-1598] Add new language as a fixed element at the end of metadata display

- package-lock.json
- package.json
- src/modules/lists/components/CitationAction/index.js
- src/modules/lists/components/PermalinkAction/index.js
This pull request removes `clipboard-polyfill`, and replaces the function with `navigator.clipboard.writeText(...)`.
- `npm run reinstall && npm start`
- Poke around [the site](http://localhost:3000/) and see if anything seems broken.
- Search for a Catalog item and see if you can copy a citation and/or link.
If you load the site and it produces this error:
- Stop the browser view (`Ctrl + C`).
- `cd node_modules/pride`
- `nano pride.js`
- Replace all instances of `_underscore._.` with `_underscore.` and save.
- `npm install`
- `cd ../../`
- `npm start`
> Update packages (March) - Part 2

- package-lock.json
- package.json
This pull request updates several React-related dependencies to the latest subversion of their current versions.
These dependencies have been upgraded to their latest versions:
- `react-ga`
- `redux` and `react-redux`
- `npm run reinstall && npm start`
- Poke around [the site](http://localhost:3000/) and see if anything seems broken.
> Update packages (March) - Part 4

- src/modules/search/search-options.js
This PR addresses [LIBSEARCH-82](https://mlit.atlassian.net/browse/LIBSEARCH-82).
> There's a redundant "Learn about the meaning of call numbers" in the hint displayed in Call Number Browse.
The tip has been updated to match what is seen on Catalog Browse.
> [LIBSEARCH-82] Update Call Number Browse hint

- src/modules/resource-acccess/components/holder.js
This PR addresses [LIBSEARCH-99](https://mlit.atlassian.net/browse/LIBSEARCH-99).
The `Location has` button has been removed, and will simply display the information by default.
> [LIBSEARCH-99] Remove 'Location Has' button from Catalog Location Holdings+Show Available Location Details on Default

- src/modules/core/components/TrimString/index.js
- src/modules/getthis/components/GetThisRecord/index.js
- src/modules/records/components/Record/index.js
- src/modules/records/components/RecordFull/index.js
- src/modules/records/components/RecordPreview/index.js
- src/modules/resource-acccess/components/holder.js
- src/stylesheets/main.css
This PR addresses [LIBSEARCH-63](https://mlit.atlassian.net/browse/LIBSEARCH-63).
Vernacular information has been added to the record titles metadata. This PR separates and styles the information according to [Figma](https://www.figma.com/file/4izNI8OilJi1MXsNKiKWhX/Library-Search-Design-System?node-id=7%3A44).
> [LIBSEARCH-63] Implement updated title & statement of responsibility displays

- src/config/config.js
- src/modules/search/components/SearchBox/index.js
- src/modules/search/search-options.js
When searching Articles by `keyword`, it searches by `exact` results. There is now an option to search for keywords it `contains`. Instead of now just having `Keyword` listed in the `select` menu, it has been replaced with two new options:
* `Keyword (is exact)`
* `Keyword (contains)`
This pull request closes [LIBSEARCH-197](https://mlit.atlassian.net/browse/LIBSEARCH-197).
`autocomplete="on"` has already existed on the search box's `input[type="text"]` element, which would show previously searched values. However, it was not trigger due to a lack of the `name` attribute. The attribute has been added to fix this issue.
This pull request resolves [LIBSEARCH-712](https://mlit.atlassian.net/browse/LIBSEARCH-712).
> [LIBSEARCH-197] Figure out the exact & contains menu structure and connect with the back end

- src/modules/search/components/SearchTip/index.js
This PR addresses [LIBSEARCH-759](https://mlit.atlassian.net/browse/LIBSEARCH-759)
`SearchTip` stopped showing up on Search. This was because the `tip` property needed to be updated to `uid`.
> [LIBSEARCH-759] Search hints in Catalog are not displaying a recent Search release

- src/modules/lists/components/CitationAction/index.js
When the “citation” action is selected in Library Search to generate a citation in MLA, Chicago, etc., style, the displayed text is plain ASCII, but the text generated when “Copy to clipboard” is selected includes HTML elements.
Example:
[https://search.lib.umich.edu/catalog/record/99187422669506381](https://search.lib.umich.edu/catalog/record/99187422669506381)
Selecting “MLA” displays this text:
`How to Read a Paper : The Basics of Evidence-Based Medicine. Fourth edition, Wiley-Blackwell, 2010.`
When the “Copy citation” button is clicked, the following text is added to the clipboard:
`<div class="csl-entry"><i>How to Read a Paper : The Basics of Evidence-Based Medicine</i>. Fourth edition, Wiley-Blackwell, 2010.</div>`
To resolve this issue, the copied text is now the `innerText` of the …
> [LIBSEARCH-785] HTML elements included when citations are copied from Library Search action bar

- public/index.html
Design System was using `unpkg` for their CDN, but has since been unsupported. They are now switching to `jsDelivr`.
This pull request updates the new CDN.
- Check the website and see if anything looks broken.
> [DS-120] Update properties to jsDelivr

- .eslintrc.json
- package-lock.json
- package.json
- src/modules/pride/utils.js
This PR addresses [LIBSEARCH-796](https://mlit.atlassian.net/browse/LIBSEARCH-796)
When selecting a collection, the query `filter.collection=` is added to the URL. The query does not exist when a collection is not originally selected by the user, but the option is set to `All collections`. When you select a collection, then go back to selecting `All collections`, then it gets treated as a collection selection and adds `filter.collection=All+collections` to the URL. This then gets processed as an active filter, and returns `0` results as there are no items that belong to the `All collections` collection.
The code has been modified so that if `collection: All collections` gets parsed, it does not get applied as an active filter.
ESLint has already existed, but the `standard` configuration …
> Libsearch 796 incorrect behavior in catalog advanced search when a collection is selected, and then reverted to all collections

- src/config/config.js
- src/modules/records/components/KeywordSwitch/index.js
- src/modules/search/components/SearchBox/index.js
- src/modules/search/utilities/index.js
This PR addresses [LIBSEARCH-818](https://mlit.atlassian.net/browse/LIBSEARCH-818).
> Exact is proving unsatisfactory to most users, most of the time. 
> ...
> Perhaps on a Netlify server… Set Keyword (Contains) to be the default Articles search behavior. 
The following changed files have fixed `eslint` errors.
> [LIBSEARCH-818] In TESTING environment, set "Keyword (contains)" as default Articles search option

- .github/workflows/build-release.yml
- .github/workflows/dockerhub-release.yaml
- .github/workflows/dockerhub-unstable.yaml
- Dockerfile
- package.json
When running a GitHub action, 9 related warnings will be displayed under Annotations:
```
build
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: docker/login-action@v1, docker/build-push-action@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
```
build
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
```
build
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: …
```
> Updating workflows.

- src/modules/records/components/RecordMetadata/index.js
- src/modules/reusable/components/Metadata/index.js
- src/modules/reusable/index.js
This PR addresses [LIBSEARCH-820](https://mlit.atlassian.net/browse/LIBSEARCH-820).
> UX research on the position and style for “Browse in call number list” shows the most discoverable position is in the record metadata component as a new metadata element, listing the unique LC and Dewey call numbers, one per line, each linked to Call Number Browse.
> [LIBSEARCH-820] Add "Browse in call number list" link to full record view

- .github/workflows/build-release.yml
[actions/upload-release-asset](https://github.com/actions/upload-release-asset) has become an unmaintained repository, and was archived March 3, 2021. The project recommends to replace the action with [softprops/action-gh-release](https://github.com/softprops/action-gh-release). This pull request replaces the archived action with the recommended action.
> Replacing `actions/upload-release-asset`

- .github/workflows/build-release.yml
- Dockerfile
- README.md
- package-lock.json
- package.json
Installing `search` has become problematic lately with dependency updates. `connected-react-router` has been preventing developers from installing dependencies with `npm install`, forcing them to install using `--legacy-peer-deps`. Overrides have been added to fix this.
> Remove need for `--legacy-peer-deps` in `npm install`.

- public/index.html
The Google Tag Manager ID has changed.
This pull request closes [LIBSEARCH-867](https://mlit.atlassian.net/browse/LIBSEARCH-867).
> [LIBSEARCH-867] Replace Google Tag Manager Tracking Code on U-M Library Search, MGet It, Askwith Media Booking Page, and Library Account

- src/modules/records/components/RecordPreview/index.js
- src/stylesheets/main.css
- src/stylesheets/search/_record-preview.scss
Adding a property in cells for links under resourceAccess data to indicate whether the link is eligible for being shown in preview renderings.
Removing the `display: inline-block` on the record-preview-link `<p>` tag.
We are adding a second link to the preview view of articles results.  Previously, preview views only showed the first link available, however, we would like to show multiple links sometimes.  Online journals already has multiple links so we can't just render every link in the list.
This pull request adds final details to [LIBSEARCH-889](https://mlit.atlassian.net/browse/LIBSEARCH-889).
List instructions on how to test the pull request. Some examples:
> Adding support for previewEligible

- src/modules/lists/components/ActionStatusMessage/index.js
When emailing a record through the `Actions` list, if there is a `status` but the `status.status_code` is `undefined`, it would throw a `console.error` and make the page go blank. That was because there was a check to see if the undefined status code had a certain string. This was found out when `/spectrum/email` was throwing a `500` error.
A check has been added to see if `status.status_code` exists. An extra check has been added to see if it begins with `'action.response.'`.
`ActionStatusMessage` has been converted to a functional component, to follow today's [React practices](https://react.dev/learn/your-first-component).
- Get the site locally up and running:
- Build the branch:
```
npm run build:dev
```
- …
> Bug: Alert will not show if `status.status_code` is undefined.

- src/modules/lists/components/ActionsList/index.js
- src/stylesheets/main.css
> Due to some Twilio configuration issues, sms messages aren't being delivered to patrons from Alma. They are getting to Twilio and then Twilio is not sending them.
>
> Some background is we needed to have our account associated with a brand, and Twilio went to verify ours on August 28 while [umich.edu](http://umich.edu/) was down and rejected our request.
This is likely to be the case for 2 - 3 weeks.
The `Text` action has been disabled until messages are able to be sent again.
This pull request resolves [LIBSEARCH-904](https://mlit.atlassian.net/browse/LIBSEARCH-904).
- Go to a record and look at the list of `Actions`.
- Is the `Text` action grayed out?
- Can you click on it?
- Is there a message underneath …
> [LIBSEARCH-904] Temporarily make "Text" action inactive and add a message to users

- src/modules/records/components/Zotero/index.js
Back in May, the `title` attribute in the `Zotero` component [was removed to resolve accessibility issues](https://github.com/mlibrary/search/commit/4d714c7fb437ba8b3711dc812a559ce79ea23896). Doing this prevents software such as Zotero from reading the citation metadata. The attribute has been restored, along with an accessibility note.
> Bug: Zotero metadata restoration

- src/modules/search/components/SearchByOptions/index.js
Catalog Browse is officially out of beta! This pull request removes everything beta related.
This pull request resolves [LIBSEARCH-926](https://mlit.atlassian.net/browse/LIBSEARCH-926).
- Run the tests to make sure they pass (`npm run test`).
- Load up [the site](http://localhost:3000/everything) and check the dropdown. Has `[BETA]` been removed?
> [LIBSEARCH-926] Deploy Browse as a full service (UI)

- src/modules/search/components/SearchBox/index.js
When going from Search to Catalog Browse, viewers briefly face a 404 page before being redirected. This pull request wraps the logic in an `if/else` statement, and also updates the location based on the current `hostname`.
- In the list of search options, select one under `Browse by`, and submit a search.
- Do you encounter a 404 page?
- Are you taken to the correct Catalog Browse page?
- Does Search work fine everywhere else?
> Bug: Browse redirect has brief 404

- src/modules/reusable/components/Metadata/index.js
Second browse links have been launched. As a result, the fielded search links disappeared. This pull request brings them back.
Before:
After:
- Check a [full record](http://localhost:3000/catalog/record/990134893780106381?query=herbert%2C+frank&library=All+libraries) to see if both fielded and browse second links appear, and are navigable.
> Bug: Adding fielded search links along side `browse` links.

- src/modules/getthis/components/GetThisOption/index.js
`summary` has been [added to Spectrum](https://github.com/mlibrary/spectrum/pull/166) to replace the existing `service_type` and `duration` properties. When this is live, the next step would be to investigate and see if the two previous properties are used elsewhere and can be safely removed.
This pull request closes [LIBSEARCH-936](https://mlit.atlassian.net/browse/LIBSEARCH-936).
- Start the site and find an item that is available through Get This. Check and see if the content has been updated. Check the site and see if anything else is broken.
> Replacing `servce_type` and `duration` with `summary`.

- src/modules/getthis/components/GetThisOption/index.js
- src/stylesheets/main.css
With `service_type` and `duration` being removed from Spectrum, `service_type` will no longer be defined, so it has been removed.
`GetThisOption` has been cleaned up and simplified.
- Select a `Get This` item and check to see if anything is broken.
> Remove remaining `service_type`

- src/modules/records/components/Zotero/index.js
`title` was not a compatible attribute with `span` as it was a non-interactive element. A work-around this warning was to add `tab-index="-1"` to the element.
- Take a look at [a record in full view](http://localhost:3000/catalog/record/11101952588?library=All+libraries&query=test). Do you still see the Zotero information? Does it match what is on [the live site](https://search.lib.umich.edu/catalog/record/11101952588?library=All+libraries&query=test)?
> Making `Zotero` pass accessibility tests.

- src/modules/pride/index.js
- src/modules/pride/setup.js
- src/modules/pride/utils.js
`Pride.FieldTree.parseField` was only ever used in Search. Instead of storing the logic in Pride, it has been moved over into a function called `prideParseField`.
- Poke around the site and see if anything is broken.
> `Pride.FieldTree.parseField` to `prideParseField`.

- src/modules/advanced/components/AdvancedSearchForm/index.js
- src/modules/affiliation/actions/index.js
- src/modules/affiliation/index.js
- src/modules/getthis/components/GetThisFindIt/index.js
- src/modules/getthis/components/GetThisPage/index.js
- src/modules/pride/components/URLSearchQueryWrapper/index.js
- src/modules/records/components/RecordFull/index.js
- src/modules/records/components/RecordList/index.js
- src/modules/records/components/Sorts/index.js
- src/modules/search/components/SearchBox/index.js
This pull request is a continuation of removing `withRouter` in order to update `history` and `react-router-dom`. These components have been rewritten to remove the need for `withRouter`:
- `AdvancedSearchForm`
- `FullRecord`
- `RecordListContainer`
- `SearchBox`
- `GetThisPage`
- `GetThisFindIt`
- `URLSearchQueryWrapper`
To align with [current React practices](https://react.dev/learn/your-first-component), these class components have been converted to functional components:
- `AdvancedSearchForm`
- `FullRecord`
- `GetThisFindIt`
- `GetThisPage`
- `URLSearchQueryWrapper`
- Poke around the site and see if anything is broken.
> `history` and `react-router-update` - Part 4

- package-lock.json
- src/modules/filters/components/Filters/index.js
- src/modules/lists/components/List/index.js
Exporting a citation through a temporary list was not working due to `datastore` not being defined in `props`. `activeDatastore` provided the same results in the props, but was not called anywhere. This pull request directly defines `datastore`, and now allows you to export citations in both temporary lists and full records. 
This pull request fixes [LIBSEARCH-947](https://mlit.atlassian.net/browse/LIBSEARCH-947).
The dropdown lists for filters while viewing records showed both up and down arrows. This has been fixed.
`npm audit fix` was also ran due to a couple of new vulnerabilities that popped up.
- Create a temporary list and try to export the citations.
- View a full record and try to export the citation.
> [LIBSEARCH-947] Button in Actions section does not activate

- .github/workflows/build-release.yml
- Dockerfile
`julep-1` and `bulleit-1` are at `node v. 20.5.1`. This pull request updates files and actions relating to the new version.
- Run the site and see if it works.
> Updating `node` to `20.5.1`.

- .github/PULL_REQUEST_TEMPLATE/dependency_updates_template.md
- package-lock.json
- package.json
- src/modules/pride/utils.js
[`jsonschema`](https://www.npmjs.com/package/jsonschema) was only ever used once in `src/modules/pride/utils.js`. The code has been replaced with vanilla JavaScript and has been uninstalled.
`url` was also never used in the repository and has been uninstalled.
- Look around the site to see if anything is broken.
> Replacing JSONSchema and URL

- .github/PULL_REQUEST_TEMPLATE/dependency_updates_template.md
- .github/pull_request_template.md
- package-lock.json
- package.json
- src/config/config.js
- src/modules/advanced/components/FiltersContainer/getFilters.js
- src/modules/advanced/reducer/index.js
- src/modules/datastores/components/DatastoreRoute/index.js
- src/modules/filters/components/Filters/styles.css
- src/modules/filters/reducer/index.js
- src/modules/lists/prejudice.js
- src/modules/pride/index.js
- src/modules/pride/setup.js
- src/modules/pride/utils.js
- src/modules/records/components/RecordList/index.js
- src/modules/records/reducer/index.js
- src/modules/records/utilities/index.js
- src/modules/reusable/underscore/index.js
- src/stylesheets/main.css
[`underscore`](https://www.npmjs.com/package/underscore) is an old library that provided many complex functions which can now be accomplished with modern JavaScript. This pull request replaces all uses of `underscore` with vanilla JavaScript, and uninstalls the package.
[`core-js`](https://www.npmjs.com/package/core-js) has been uninstalled as it was not being used anywhere.
Some unused functions were deleted. A couple of CSS bugs were also fixed.
- Look around the site and see if anything is broken.
> Replacing `underscore` with vanilla JavaScript.

- .github/PULL_REQUEST_TEMPLATE/dependency_updates_template.md
- eslint.config.mjs
- package-lock.json
- package.json
- src/modules/advanced/components/FiltersContainer/getFilters.js
- src/modules/filters/reducer/index.js
- src/modules/lists/prejudice.js
- src/modules/pride/setup.js
- src/modules/pride/utils.js
When setting up the new `eslint`, a lot of rules went away. This pull request reinstalls these two plugins and applies all of the original rules from [`eslint-config-standard`](https://github.com/standard/eslint-config-standard/blob/master/src/index.ts):
- `eslint-plugin-import`
- `eslint-plugin-n`
- Run `npm run lint` and `npm run lint:fix` to see if it works.
> Eslint standard rules

- src/modules/lists/components/ActionsList/index.js
- src/modules/lists/components/EmailAction/index.js
- src/modules/lists/components/TextAction/index.js
When using an Email or Text action on a record, it would produce this error:
```
TypeError: Cannot read properties of undefined (reading 'email')
```
This pull request adds a check to see if `profile` exists, along with the `email` or `text` properties. If so, get the values. If not, default to an empty string.
> TypeError: Cannot read properties of undefined (reading 'email')

- src/modules/resource-acccess/components/Holding/index.js
To simplify Google Tag Manager triggers, the class `access-link-cell` has been added to the first column of every `Holding` row in `tbody`.
This pull request resolves [LIBSEARCH-987](https://mlit.atlassian.net/browse/LIBSEARCH-987).
- Check a record that has holdings. Inspect the element that has the link Get This, Available online, Go to item, Go to database, Go to online journal, Request access, etc. and see if its parent cell has the class `access-link-cell`.
> [LIBSEARCH-987] Add a Class to <a> element in the "Resource Access" component

- src/modules/browse/components/ShelfBrowseCarousel/index.js
- src/stylesheets/utilities.css
When navigating `ShelfBrowseCarousel` by keyboard, there is no `focus` state for the cards. This pull request creates a `.focus` class 
- View a full catalog record and tab through it with the keyboard. Does an outline show around the cards?
> Creating `.focus` style and applying to cards.

- src/modules/advanced/reducer/index.js
- src/stylesheets/forms.css
When adding multiple query options to search, when you start typing, the boolean type (`AND`, `OR`, `NOT`) disappears. You then cannot select `AND`. Two problems were discovered in the `reducer`:
1) `state[dsUid].fieldedSearches[index].booleanTypes` does not exist, making `booleanType` return `undefined`.
2) The `booleanType ? ...` ternary operator returns `false` when set to `AND` because the `value` of `AND` is `0`, which is also equivalent to `false`. It now specifically checks if it is a number and is less than the number of available boolean types to prevent the use of a magic number that does not exist as a type.
Focusing on a radio button turned the button into a square. That is because of the `:focus` pseudo-class defining `border-radius: 2px`. Adding `border-radius: …
> Bug: Advanced Search boolean types get deselected or cannot get reselected.

- src/modules/advanced/components/FieldInput/index.js
- src/modules/advanced/components/NarrowSearchTo/index.js
- src/modules/datastores/components/Landing/index.js
- src/modules/getthis/components/GetThisForm/index.js
- src/modules/institution/components/InstitutionSelect/index.js
- src/modules/institution/components/InstitutionSelect/styles.css
- src/modules/records/components/Sorts/index.js
- src/modules/search/components/SearchBox/index.js
- src/modules/search/components/SearchBox/styles.css
- src/stylesheets/forms.css
- src/stylesheets/main.css
- src/stylesheets/utilities.css
The `select` HTML element was the only remaining form element that did not have dedicated global styling. This pull request adds that and cleans up components that were using other styles and structures to help simplify.
- Check the site and see if `select` elements have the new styling and still work as intended.
> Styling `select` elements.

- src/modules/resource-acccess/components/Holder/styles.css
Poorly formatted data does not wrap in Holdings, causing the text to overlap other cells. You can see [an example](https://search.lib.umich.edu/catalog/record/990039295180106381) under the last Buhr Shelving Facility accordion:
This pull request adds `overflow-wrap: anywhere` to the table cells, forcing wrapping to happen when appropriate. This resolves the [TDX Ticket 6898877](https://teamdynamix.umich.edu/TDNext/Apps/87/Tickets/TicketPeople?TicketID=6898877)
- Check the live example above and compare it with the [dev example](https://deploy-preview-476--umich-lib-search-dev.netlify.app/catalog/record/990039295180106381?query=title%3A(Announcement.)&filter.author=University+of+Michigan.+Center+for+Japanese+Stud …
> TDX 6898877: Library Search Feedback - poor display of multiple volumes

- src/config.js
- src/modules/filters/components/CheckboxFilters/index.js
- src/modules/filters/components/CheckboxFilters/styles.css
- src/modules/resource-acccess/components/Holders/index.js
> It is currently “Remove search only HathiTrust materials” and checked by default.
> 
> We want to change it to “View HathiTrust search-only materials” and have it Unchecked by default
This pull request resolves [LIBSEARCH-958](https://mlit.atlassian.net/browse/LIBSEARCH-958).
> [LIBSEARCH-958] Implement new availability filters in the UI

- src/modules/affiliation/components/ChooseAffiliation/index.js
- src/modules/profile/components/Authentication/index.js
- src/modules/records/components/BentoboxList/index.js
- src/modules/records/components/ILLRequestMessage/index.js
- src/modules/records/components/RecordList/index.js
- src/modules/records/index.js
The Interlibrary Loan request message for zero results also needed to be added to the Catalog section of Everything. To reduce repetition, the `ILLRequestMessage` component has been created and applied to wherever necessary.
This pull request closes [LIBSEARCH-998](https://mlit.atlassian.net/browse/LIBSEARCH-998).
- Make a zero results search. Does the message appear in all datastores?
> [LIBSEARCH-998] Add link to I.L.L. for the "no results" message in all four search types (part 2)

- src/modules/datastores/components/DatastoreRoute/index.js
- src/modules/pride/components/URLSearchQueryWrapper/index.js
> ...the Search front-end is producing spurious search queries to the backend.
>
> For example, loading the welcome page https://search.lib.umich.edu/ initiates searches.  It looks like it started in v1.15.35.
[v1.15.35](https://github.com/mlibrary/search/releases/tag/v1.15.35) was a major update, but the problem existed `URLSearchQueryWrapper`. It was updating whether or not the URL had any valid query parameters. The logic has been updated to check for parameters, and then run search of any of the `updateRequired` properties were `true`.
* `DatastoreRoute` has been simplified.
* `datastoresUid` has been memoized to avoid unnecessary recalculations.
- Run the site.
- Does `/everything` no longer fetch every …
> Bug: Search initiated when no query 

- src/modules/pages/components/AccessibilityPage/index.js
Updating WCAG standards to 2.1. Updated link to match [Lib's Accessibility page](https://lib.umich.edu/about-us/about-library/diversity-equity-inclusion-and-accessibility/accessibility).
This pull request closes [LIBSEARCH-1029](https://mlit.atlassian.net/browse/LIBSEARCH-1029).
- Check the [Accessibility](http://localhost:3000/accessibility) page and see if the text and link have been updated.
> [LIBSEARCH-1029] Update Accessibility page to refer to "WCAG 2.1AA"

- .github/workflows/dependabot.yml
When running the `dependabot` workflow, in `Update PR title`, this error gets produced:
```json
{
"message": "Resource not accessible by integration",
"documentation_url": "https://docs.github.com/rest/pulls/pulls#update-a-pull-request",
"status": "403"
}
```
To help resolve the issue, we are adding permissions to the workflow.
> Adding permissions.

- src/modules/advanced/components/AdvancedSearchContainer/index.js
- src/modules/advanced/components/AdvancedSearchContainer/styles.css
- src/modules/advanced/components/AdvancedSearchForm/index.js
- src/modules/advanced/components/AdvancedSearchForm/styles.css
- src/modules/advanced/components/FiltersContainer/index.js
- src/stylesheets/main.css
- src/stylesheets/spacing.css
- src/stylesheets/utilities.css
The current Advanced Search uses tabs to quickly navigate between each datastore option. However, it creates confusion because you may be on one datastore, but end up searching in a different datastore. We want to clarify which datastore you are on and pull in active filters from the datastore, with that also being reflected in the URL. We instead turn the tabs into links.
Some subtle styles have also been updated.
The next step is to take the datastore's active filters and have them reflected in the form on load.
- Make a filtered search in multiple datastores. Go to Advanced search. Do you see the filter options in the URLs as you navigate?
- Does it still look and feel similar to the live site?
> [LIBSEARCH-801] Implement "clear active filters" designs for advanced search (Part 1)

- src/modules/advanced/components/AdvancedSearchContainer/index.js
- src/modules/advanced/components/AdvancedSearchForm/index.js
- src/modules/advanced/components/FieldInput/index.js
- src/modules/reusable/components/Breadcrumb/index.js
- src/modules/search/components/SearchBox/index.js
- src/modules/search/components/SearchByOptions/index.js
This pull request focuses on increasing performance of the overall Advanced Search pages. Below are the noted changes:
- `removeFieldedSearch`, and `setFieldedSearch` have been moved to `FieldInput` as those functions are only ever handled in that component.
- `removeUndefinedFilters` logic has been updated and applied directly to `activeFilters`.
- `FieldInput` and `SearchByOptions` only ever use the `uid` of the current datastore. Instead of passing in the entire object, only the string gets passed in.
- Object destructuring to reduce repeated code.
- Wrapped `FieldInput` in `memo` to prevent unnecessary re-renders when the props haven't changed.
- Go to Advanced Search. Doe everything work as expected?
> [LIBSEARCH-801] Implement "clear active filters" designs for advanced search (Part 2)

- src/modules/advanced/components/AdvancedFilter/index.js
- src/modules/advanced/components/FiltersContainer/index.js
- src/modules/core/components/DateRangeInput/index.js
- src/modules/core/components/Multiselect/index.js
- src/modules/records/components/Pagination/styles.css
- src/stylesheets/main.css
This pull request focuses on making changes to the `DateRangeInput` component. Below are the noted changes:
- Separated `DateRangeInput` from `AdvancedFilter` for easier access and control.
- Updated `DateRangeInput` to use `number` input types instead of text.
- Added styles for `input[type="number"]`.
- Updated `Multiselect` with simpler logic, and to set advanced filters on load based on the current filters set by the URL.
- Moved logic for grabbing current and advanced filters into `FiltersContainer`  to resolve the `Selector unknown...` warning.
- Check advanced search and compare it to the current site.
- Does it look and feel the same?
- If there are filters set, do they carry throughout the datastore?
- …
> [LIBSEARCH-801] Implement "clear active filters" designs for advanced search (Part 4)

- public/index.html
The Hotjar license has been cancelled, and has been replaced by Microsoft Clarify. As a result, the Hotjar script needs to be removed as it's not longer being used.
This pull request closes [LIBSEARCH-1040](https://mlit.atlassian.net/browse/LIBSEARCH-1040).
- Run the site and check if anything is broken.
> [LIBSEARCH-1040] Remove Hotjar Tracking Code from U-M Library Search

- src/modules/lists/components/CitationAction/index.js
This sentence with a link has been added to the Cite Action:
> View the [Citation Management guide on U-M Library Website (opens in new tab)](https://lib.umich.edu/research-and-scholarship/help-research/citation-management).
This pull request closes [LIBSEARCH-950](https://mlit.atlassian.net/browse/LIBSEARCH-950).
- View a record and check the `Citation` tab under `Actions`.
- Do you see the new text in the description?
- Does the link work?
> [LIBSEARCH-950] Add link to Citation assistance to Cite Action pane

- src/modules/core/components/SearchHeader/index.js
- src/modules/datastores/components/FlintAlerts/index.js
- src/modules/lists/components/ActionsList/index.js
- src/modules/pages/components/DatastorePage/index.js
- src/modules/pride/setup.js
- src/modules/profile/components/AuthenticationRequired/index.js
> Profile data is loaded asynchronously after the initial load of Search data (datastore information, filters, etc.). If a user is authenticated with co-sign, but the Search UI doesn't know if this yet, this would cause unnecessary rerouting to login.
The app has been updating to synchronously run all `setup` functions before running `renderApp`. The `Log in/out` button in the header also no longer shows until the `profile` state has finished loading. All other components using the `profile` state have been modified to bring in the necessary data instead of the full object.
This pull request resolves [LIBSEARCH-61](https://mlit.atlassian.net/browse/LIBSEARCH-61).
- Look through the site and check if everything …
> [LIBSEARCH-61] Investigate ways to overcome late loading of profile data

- src/modules/records/components/RecommendedResource/index.js
- src/modules/records/components/Record/index.js
- src/modules/records/components/RecordFull/index.js
- src/modules/records/components/RecordMetadata/index.js
- src/modules/records/components/RecordPreview/index.js
- src/modules/records/components/Zotero/index.js
- src/modules/reusable/components/Metadata/index.js
The length of authors does not have a limit. This can be problematic when seeing [results with many authors](https://search.lib.umich.edu/everything?query=HIV+Prevalence+Incidence+Mortality+Trends+US). This pull request specifically looks for `author` in `Medium` or `Preview` record views and uses the `TrimString` component.
This pull request fixes [LIBSEARCH-968](https://mlit.atlassian.net/browse/LIBSEARCH-968).
Multiple components were pulling in the entire `record` object, when they only needed one property from it. They have been updated to only pull in the necessary information.
- Search [a query with a lengthy amount of authors](http://localhost:3000/everything?query=HIV+Prevalence+Incidence+Mortality+Tren …
> [LIBSEARCH-968] Articles results in Everything results view have no truncation on author data displayed

- src/modules/browse/organizeByParents.js
If it lists parents, but none are found, then it's a top level parent.
This change prevents a middle level showing up as a top level, too if one parent isn't found.
There's no UI changes other than how some terms are organized.
> Invert the logic on whether it's a top-level

- .github/workflows/update-csl.yml
This runs `npm run update:csl` and creates a new PR if there are changes in `public/citations`.
Scheduled to run monthly.
> Add a workflow for updating csl files

- src/modules/records/components/Metadata/index.js
When viewing a `Preview` or `Medium` record, by default, each individual piece of `metadata` gets trimmed if the length of text goes beyond 240 characters. If a record has [multiple summaries](https://search-staging.www.lib.umich.edu/catalog?query=MUMBO+JUMBO+GUMBO+WORKS%3A+THE+KALEIDOSCOPIC+FICTION+OF+ISHMAEL+REED+.%E2%81%A9), each individual summary gets trimmed and displayed instead of being viewed as a whole block of text.
To resolve this, the `metadata` only shows the first summary if not viewing a `Full` record, which gets trimmed if necessary.
- Check a record with [multiple summaries](http://localhost:3000/catalog?query=MUMBO+JUMBO+GUMBO+WORKS%3A+THE+KALEIDOSCOPIC+FICTION+OF+ISHMAEL+REED+.%E2%81%A9).
- …
> Bug: Individual `Summary` entries get trimmed, instead of full collection.

- src/modules/records/components/RecordFull/index.js
Viewing a [full Online Journal record](https://search.lib.umich.edu/onlinejournals/record/99187579295006381) does not display because of this error:
```
Uncaught TypeError: Cannot destructure property 'name' of 'At(...)' as it is undefined.
at index.js:204:23
at da (index.js:203:23)
```
This was because `findWhere(record.fields, { uid: 'indexing_date' })` would return `undefined`. An empty object has been added as a backup.
The `inDatastore` check has been removed. It will now display on any record where the field exists.
- Check a [full Online Journal record](http://localhost:3000/onlinejournals/record/99187579295006381)  and see if you can view it.
- Check any other record to see if they still display.
> Bug: Full ROnline Journals records do not display from lack of `indexing_date`.

- src/modules/records/components/Record/index.js
For Article records, the full record displays the `abstract` field below the `title`. In the medium view, the `abstract` field is in the `metadata` list. This pull request moves the trimmed `abstract` field underneath the record's `title` on medium views to reflect the full record's structure.
This pull request fixes [LIBSEARCH-1052](https://mlit.atlassian.net/browse/LIBSEARCH-1052).
[Spectrum](https://github.com/mlibrary/spectrum/blob/main/config/fields.yml#L869) needs to be updated to remove the field from the view.
- Check out list of articles results.
- Do you see the abstract underneath the title in medium views?
- Do you still not see it in preview views?
- Do you still see it in full record?
> [LIBSEARCH-1052] Change position of Abstract in Articles medium view results

- src/modules/records/components/RecordFull/index.js
> **Problem Statement**
> 
> We do not shown the "View MARC data" link on records in the Online Journals portion of Library Search; that is only available in Catalog. The reason originally was, pre-Alma, that Online Journals was searching and displaying a limited set of metadata that was extracted from Aleph. As part of the migration to Alma, we changed Online Journals to be a subset of catalog data, rather than a specially-created separate, limited, index. Online Journals records are basically otherwise identical to Catalog Records in most respects.
> 
> **Success Criteria**
> 
> Add the “View MARC data” button that currently appears beneath holdings in Catalog records in the same position on Online Journals records.
Showing the `ViewMARC` component was controlled by making sure the …
> [LIBSEARCH-1081] Add "View MARC data" button to Online Journal records (bring into alignment with Catalog)

- src/modules/lists/components/CitationAction/index.js
> Update the link displayed in the Actions bar to https://guides.lib.umich.edu/citationhelp 
This pull request resolves  [LIBSEARCH-1091](https://mlit.atlassian.net/browse/LIBSEARCH-1091).
- Check a full record, and open the `Citations` tab in the `Actions` bar. Does the link go to https://guides.lib.umich.edu/citationhelp?
> [LIBSEARCH-1091] Change link to citation help

- src/modules/getthis/components/GetThisForm/index.js
When a patron chooses the "Request for pickup at the library" option in Get This, they get the option to choose where they would like it picked up, along with a "Cancel this hold if item is not available before" date selector. This pull request updates the form that sets a `min` attribute to be two weeks after the current date, disabling the ability for a patron to choose the next day.
This pull request resolves [LIBSEARCH-1097](https://mlit.atlassian.net/browse/LIBSEARCH-1097).
- Click on a `Get This` link for a catalog record. Log in and select the `Request for pick up at a library` accordion. Change the date in the "Cancel this hold if item is not available before" input. Can you select the date earlier than …
> [LIBSEARCH-1097] Change "cancel" date in Get This Request for Pickup in a Library to be no sooner than 2 weeks away
